In [ ]:
%pip install numpy

In [12]:
import numpy as np
Aleatorio = np.random.randint(0,101,10) #Gera 10 numeros aleatorios de 0 a 100
print(f'Números aleatórios: {Aleatorio}')
print(f'Tipo do dado: {Aleatorio.dtype}')

Números aleatórios: [ 56  64  94  38  69  69  54 100  70  85]
Tipo do dado: int32


In [15]:
matriz = np.random.rand(5,5) #Gera valores aleatórios de 0,1
min = matriz.min()
max = matriz.max()
med = matriz.mean()

print(f'Matrix: {matriz}')
print(f'Minimo: {min}')
print(f'Maximo: {max}')
print(f'Média: {med}')


Matrix: [[0.80583887 0.20871315 0.39387412 0.23171827 0.35635331]
 [0.14979881 0.83217734 0.8743029  0.7171097  0.28053542]
 [0.79543149 0.29868523 0.56740254 0.43978915 0.74033115]
 [0.90430271 0.46874121 0.58601865 0.97277287 0.44464238]
 [0.17628465 0.3232697  0.23978613 0.18312869 0.05047177]]
Minimo: 0.05047176686611554
Maximo: 0.9727728731786516
Média: 0.4816592078439089


In [26]:
Aleatorio = np.random.rand(10) 
print(Aleatorio)
MultArray = Aleatorio * 10
print(MultArray)

[0.8687411  0.24539594 0.36131984 0.64214236 0.54135325 0.77088945
 0.65108832 0.41582746 0.15399671 0.14359426]
[8.68741103 2.45395944 3.61319843 6.4214236  5.41353247 7.7088945
 6.51088322 4.15827456 1.53996712 1.4359426 ]


In [24]:
array_sh = np.random.randint(0,10,(3,3))
print(array_sh)



[[6 8 4]
 [1 2 3]
 [2 3 6]]


In [ ]:
array = np.random.randint(0, 9, size=(3, 3))
print(array)

array[1] = -1
print(array)